### ISSUE TITLE
Failed to setup tbf because of Invalid authentication credentials

### ISSUE THREAD

**Issue by kenhys** [mpppk/tbf#25]
# Problem

`go get github.com/mpppk/tbf` fails unexpectedly.

# Actual

```
% go get github.com/mpppk/tbf
# cd .; git clone https://go.googlesource.com/image /home/kenhys/work/golang/gopath/src/golang.org/x/image
Cloning into '/home/kenhys/work/golang/gopath/src/golang.org/x/image'...
fatal: remote error: 


Invalid authentication credentials.

Please generate a new identifier:
  https://go.googlesource.com/new-password


package golang.org/x/image/bmp: exit status 128
package golang.org/x/image/tiff: cannot find package "golang.org/x/image/tiff" in any of:
        /home/kenhys/.anyenv/envs/goenv/versions/1.10.1/src/golang.org/x/image/tiff (from $GOROOT)
        /home/kenhys/work/golang/gopath/src/golang.org/x/image/tiff (from $GOPATH)
# cd .; git clone https://go.googlesource.com/text /home/kenhys/work/golang/gopath/src/golang.org/x/text
Cloning into '/home/kenhys/work/golang/gopath/src/golang.org/x/text'...
fatal: remote error: 


Invalid authentication credentials.

Please generate a new identifier:
  https://go.googlesource.com/new-password


package golang.org/x/text/transform: exit status 128
package golang.org/x/text/unicode/norm: cannot find package "golang.org/x/text/unicode/norm" in any of:
        /home/kenhys/.anyenv/envs/goenv/versions/1.10.1/src/golang.org/x/text/unicode/norm (from $GOROOT)
        /home/kenhys/work/golang/gopath/src/golang.org/x/text/unicode/norm (from $GOPATH)
go get github.com/mpppk/tbf  4.54s user 1.39s system 16% cpu 36.284 total
```

# Expected

```
% go get github.com/mpppk/tbf
```

succeeds without "Invalid authentication credentials." error.

# Additional information

It seems that this error is raised from no credentials to clone from googlesource.com, but I don't know well about googlesource.com so I can't find this is intended behavior or not. Is it common to setup credential for cloning from above repository?

**Comment by mpppk** [comment]
Thank you for your report, and sorry for late reply.
`mpppk/tbf` does not require any authorization, so I suppose the issue might be occurred from your git setting.

Please execute `git config --global --list`, check the filename specified as`http.cookieFile`, then check whether it contains the line `go.googlesource.com`.
If you found, rename (or just remove) the file, then try `go get` again 😃

ref:
https://git-scm.com/docs/git-config#git-config-httpcookieFile
https://groups.google.com/forum/#!topic/golang-nuts/bCBCsSEQVCI

**Comment by kenhys** [comment]
> Please execute git config --global --list, check the filename specified ashttp.cookieFile, then check whether it contains the line go.googlesource.com.
If you found, rename (or just remove) the file, then try go get again

That's it!
Thank you for kindly advice. I could solve this issue now.

I'll close issue. :smiley:
